services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rekammedis_backend
    restart: always
    environment:
      - APP_PORT=8001
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=ardaganteng
      - DB_NAME=rekam_medis
      - GOOGLE_APPLICATION_CREDENTIALS=/app/rekamGo.json
    ports:
      - "8001:8001"
    networks:
      - rekammedis_net

networks:
  rekammedis_net:
    external: true
    name: rekammedis_net
