version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: rekammedis_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ardaganteng
      MYSQL_DATABASE: rekam_medis
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: rekammedis_pma
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ardaganteng
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rekammedis_backend
    restart: always
    environment:
      - APP_PORT=8001
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=ardaganteng
      - DB_NAME=rekam_medis
      - GOOGLE_APPLICATION_CREDENTIALS=/app/serviceAccountKey.json
    ports:
      - "8001:8001"
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    build:
      # Mencari folder frontend di sebelah folder backend
      context: ../front_end
      dockerfile: Dockerfile
      args:
        VITE_API_URL: /api/v1
    container_name: rekammedis_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
